keys:
  - &users:
    - &klowdo age1xp5xypym54k4svxs7f4kad4pfkfx6uwgcjeh5ut9p9rhnhc7sa8s9ag868
  - &hosts:
    - &dellicious age13ph0tj5f8k752hure0wrw38g3g4ydmugew4exd8rahh95ngsfuvsyfjnvj


creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *klowdo
          - *dellicious

