# vim: ft=hyprlang
# Auto-configure all connected monitors
monitorv2 {
  output = desc:Samsung Display Corp. 0x414D
  mode = 3456x2160@60
  position = 0x0
  scale = 1.5
}
monitorv2 {
  output = *
  mode = preferred
  position = auto
  scale = 1
}

{{if isLidClosed}}
monitorv2 {
  output = desc:Samsung Display Corp. 0x414D
  disabled = true
}
{{end}}
