# vim: ft=hyprlang
monitor = desc:Philips Consumer Electronics Company 32M2N8900 AU42435000732, 3840x2160@120, 0x0, 1.0
{{if isLidClosed}}
monitor = desc:Samsung Display Corp. 0x414D, disable
{{else}}
monitor = desc:Samsung Display Corp. 0x414D, 3456x2160@60, 3840x0, 1.5
{{end}}
