# vim: ft=hyprlang
monitorv2 {
  output = desc:Samsung Electric Company SAMSUNG 0x01000E00
  mode = 3840x2160@30
  position = 0x0
  scale = 1.5
}
{{if isLidClosed}}
monitorv2 {
  output = desc:Samsung Display Corp. 0x414D
  disabled = true
}
{{else}}
monitorv2 {
  output = desc:Samsung Display Corp. 0x414D
  mode = 3456x2160@60
  position = 0x2160
  scale = 1.5
}
{{end}}

# Lid close: lock (template disables laptop display)
# bindl = ,switch:on:Lid Switch, exec, lock-screen
# Lid open: template re-enables laptop display automatically
