---
name: Run renovate

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]
  schedule:
    - cron: "30 00 * * 0"

jobs:
  renovate:
    if: >-
      github.event_name != 'pull_request' ||
      (github.event.pull_request.merged == true &&
       startsWith(github.event.pull_request.head.ref, 'renovate'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v46.1.4
        with:
          configurationFile: .github/renovate-nix.json5
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^nix-shell .+$", "^bash .+$"]'
          RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: "true"
          RENOVATE_CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
